language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to create virtual environment
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - pytest
